version: 2
jobs:
  build:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - checkout
    - attach_workspace:
        at: ~/sls
    - run:
        name: Install NPM
        command: |
          cd application
          npm install
          npm run build
  test:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: run tests
        command: |
          #cd application
          #npm run tests
          echo "TODO"

  deploy:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: Deploy Cloudformation
        command: |
          sudo npm install -g cfn-create-or-update
          cfn-create-or-update --stack-name exporo-spa-vuetify --template-body file://cloudformation.yml --parameters ParameterKey=DomainName,ParameterValue=\"techdev2.exporo.de\" ParameterKey=BucketName,ParameterValue=\"exporo-tax-spa\" ParameterKey=PreviewDomainName,ParameterValue=\"dev.spa.techdev2.exporo.de\" ParameterKey=ProductionDomainName,ParameterValue=\"spa.techdev2.exporo.de\" ParameterKey=AcmCertificateArn,ParameterValue=\"arn:aws:acm:us-east-1:532306144703:certificate/fc32687d-1eb1-421e-8af3-0fd20c0246d9" --region eu-central-1
    - run:
        name: Deploy Preview
        command: |
          cd application
          aws s3 cp --recursive ./application/dist/ s3://exporo-webapp/build-artifacts/$CIRCLE_BRANCH
        no_output_timeout: 2m

  deployProd:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - name: Deploy Prod
      command: |
        cd application
        aws s3 cp --recursive ./dist/ s3://exporo-webapp/build-artifacts/production
      no_output_timeout: 2m

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build

    - deploy:
        requires:
        - test

    - hold:
        type: approval
        requires:
        - deploy
        filters:
          branches:
            only: master

    - deployProd:
        requires:
        - hold
        filters:
          branches:
            only: master
