version: 2
jobs:
  build:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - checkout
    - attach_workspace:
        at: ~/sls
    - run:
        name: Install NPM
        command: |
          cd application
          npm install
          npm run build
    - persist_to_workspace:
        root: .
        paths: .

  test:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: run tests
        command: |
          #cd application
          #npm run tests
          echo "TODO"

  deploy:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - run:
        name: Install cfn-create-or-update
        command: |
          sudo npm install -g cfn-create-or-update
    - run:
        name: Deploy Cloudformation
        command: >
          cfn-create-or-update --stack-name exporo-spa-vuetify --wait --template-body file://cloudformation.yml --region eu-central-1 --parameters
          ParameterKey=DomainName,ParameterValue=\"techdev2.exporo.de\"
          ParameterKey=PreviewDomainName,ParameterValue=\"spa-dev.techdev2.exporo.de\"
          ParameterKey=ProductionDomainName,ParameterValue=\"spa.techdev2.exporo.de\"
          ParameterKey=AcmCertificateArn,ParameterValue=\"arn:aws:acm:eu-central-1:532306144703:certificate/6763af47-3128-4416-8840-d866a6e800cb\"
    - run:
        name: Deploy Preview
        command: |
          cd application
          aws s3 cp --recursive ./application/dist/ s3://exporo-webapp/build-artifacts/$CIRCLE_BRANCH
        no_output_timeout: 2m

  deployProd:
    working_directory: ~/sls
    docker:
    - image: registry.gitlab.com/exporo/circleci-stretch-node-awscli:latest
    steps:
    - attach_workspace:
        at: ~/sls
    - name: Deploy Prod
      command: |
        cd application
        aws s3 cp --recursive ./application/dist/ s3://exporo-webapp/build-artifacts/production
      no_output_timeout: 2m

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build

    - deploy:
        requires:
        - test

    - hold:
        type: approval
        requires:
        - deploy
        filters:
          branches:
            only: master

    - deployProd:
        requires:
        - hold
        filters:
          branches:
            only: master
